[workspace]
members = [
    "abi-gen",
    "abi-codec",
    "prelude",
    "primitives",
    "alloc",
    "lang",
    "ty_mapping",
    "macro",
]
exclude = [
    "examples",
]

[profile.release]
panic = "abort"
lto = true
