[workspace]
members = [
    "abi-gen",
    "abi-coder",
    "prelude",
    "primitives",
    "alloc",
    "core",
    "lang",
]
exclude = [
    "examples",
]

[profile.release]
panic = "abort"
lto = true